### ISSUE TITLE
Filter Difficulties

### ISSUE THREAD

**Issue by zealousduck** [tamber/tamber-node#2]
Hi all.

I'm new to Tamber and am trying to form a filter around a number property being greater than 0. I'm attempting to use the following code ([based on the age-recommendation tutorial](https://tamber.com/docs/guides/recommend_by_age.html)):

```js
var userId = 'foo';
var count = 5;
var filter = { 
	gt: [
		{property: "num"},
		0
	]
};
tamber.discover.recommended({
		'user': userId,
		'number': count,
		'filter': filter
	}, function(err, result) { 
                // ...
        }
);
```

As a sanity check, I used `tamber.item.retrieve` to verify that my items exist. This is basically what I'm receiving back from Tamber:

```
{
  "id": "insertIdHere",
  "object": "item",
  "properties": {
   "num": 5,
   "rating": 10
  },
  "tags": ["foo","bar"],
  "popularity": 0.9751131055535003,
  "hotness": 0.5113000522579753,
  "hidden": false,
  "created": 1507688240
}
```

I'd expect that at least this item would be returned (since `num > 0`) but `tamber.discover.recommended` returns an empty array as a `result`. I tried also with `tamber.discover.next` but got the same empty `result`.

I'd appreciate any and all help with this!

**Comment by alexi** [comment]
Hi @zealousduck, welcome to tamber!  It is possible that the item with property `num` set to 5 is just not recommended to the user – meaning there is no sufficiently significant correlation between the user and the given item. Try calling `tamber.discover.popular` with the same filter and see if it comes up.

If that doesn't work, email us at team@tamber.com with your project key and we'll investigate further :)

**Comment by zealousduck** [comment]
Hi @alexi. Thanks for the suggestion! `tamber.discover.popular` did work, but I'm not sure I understand why the other methods didn't.

Does Tamber require a correlation threshold before it'll recommend items through `recommended` or `next`?

I already attempted to seed Tamber with some fake historical data (just to see what would happen), but those two methods still didn't work.

**Comment by alexi** [comment]
Yes, Tamber uses a form of thresholding.  I recommend using a test dataset to play around with to get more realistic behavior – we have a [steam video game dataset on Kaggle ](https://www.kaggle.com/tamber/steam-video-games) that is fun to play around with. 

It's over the free tier event limit, so here is a promo code for 2 free weeks of Tamber: `021` (code expires 2/1/2018). To apply the code, go to your account in the dashboard (top right) and scroll down to promo codes.
